### ISSUE TITLE
How to use for vanilla K,L LSH with precomputed hashes

### ISSUE THREAD

**Issue by paul-sud** [ritchie46/lsh-rs#1]
Hello,

I'm curious to see if I can get this to work with plain `K, L` parametrized LSH. The setup is that I already have L `Vec`s each with K (u32) hashes of the input sample, which I'd like to be able to feed directly into the LSH. The LSH hasher in this case then only queries for exact matches in each of the `L` hash tables and returns the union of all matches across all tables.

Is such a setup possible using the current API?

Thanks,

Paul

**Comment by ritchie46** [comment]
Hmm.. The LSH struct does need to know about your hashing function to be able to query. If you have a hashing function, you can implement the [VecHash](https://docs.rs/lsh-rs/0.2.3/lsh_rs/trait.VecHash.html) trait for that hashing function. The `.hash_vec_query` and `.hash_vec_put` functions are probably the same hashing function (they only differ for asymptotic LSH). Then you can instantiate a new `LSH` struct with your `CustomHasher`:

```rust
let mut lsh: LSH<MemoryTable, CustomHasher> = LshMem::new(n_projections, n_hash_tables, dim)
```
Does that help your case?

**Comment by paul-sud** [comment]
Thanks, that's definitely a good starting point, although my inputs are `&[u32]`, not `&[f32]` per the trait. I guess I can just cast though.

**Comment by ritchie46** [comment]
Yeah.. for now, I don't feel the extra complexity of generic inputs weighs up against an easy cast. :)

**Comment by paul-sud** [comment]
I wholeheartedly concur, I tried futzing with the source to make the trait generic and it got complicated very quickly. Thanks again for the help.

**Comment by ritchie46** [comment]
In case you are still interested. After some sweat, the crate is now generic for most numeric types. https://github.com/ritchie46/lsh-rs/pull/3

**Comment by paul-sud** [comment]
> In case you are still interested. After some sweat, the crate is now generic for most numeric types. #3

That's great news! I actually realized at some point that the particular hashing method I was using is incompatible with the LSH data structure in this crate, since the hashers can't execute independently. I do have other ideas where the generics would help though, thanks for the update.
