### ISSUE TITLE
how to add more 

### ISSUE THREAD

**Issue by JoungheeKim** [ritchie46/lsh-rs#8]
Hi, i'm python user.
I am enjoy to use your wonderful algorithm.

While using it, i got some question.
Is there any function that add samples after indexing

for example
-----------------------------------------------
lsh = SRP(n_projections=19, n_hash_tables=10)
lsh.fit(data_points)

lsh.add_data_points(data)    <-- such as this function
-----------------------------------------------
after build like this.
i want to add some data_points again.
but i don't want indexing all data_points that already indexed.
so i just wondered there might be some function that can add moer data points.

Thanks for your help.

**Comment by ritchie46** [comment]
Sorry for my late reaction, but have you tried `lsh.store_vec(..)`?
